// Main Image file must be put in /public/Home/WebsiteProjects/
// Extra images file must be put in /public/Home/WebsiteProjects/Extra

export default [
  {
    title: "I'm Slime",
    desc: "Online Web Multiplayer Game",
    youtubeID: "F0mAtFBdw5w",
    websiteLink: null,
    logoPath: "React.png",
    imageFileName: "ImSlimeMain.jpg",
    extraImages: ["ImSlimeE1.jpg", "ImSlimeE2.jpg", "ImSlimeE3.jpg"],
  },
  {
    title: "Zekka",
    desc: "RPG coin dozer with events",
    youtubeID: "J1YpuKkc3ng",
    websiteLink: null,
    logoPath: "UEWhite.png",
    imageFileName: "CoinDozerGame.jpg",
    extraImages: [
      "CoinDozerGameE1.jpg",
      "CoinDozerGameE2.jpg",
      "CoinDozerGameE3.jpg",
    ],
  },
  {
    title: "My Portfolio V2",
    desc: "My second portfolio website",
    youtubeID: "0saw1cGIl1A",
    websiteLink: "https://kaitosugimura.github.io/",
    logoPath: "JavaScript.png",
    imageFileName: "KaitoWebsite2.jpg",
    extraImages: [
      "KaitoWebsite2E1.jpg",
      "KaitoWebsite2E2.jpg",
      "KaitoWebsite2E3.jpg",
    ],
  },

  {
    title: "Immortal",
    desc: "Hack n'slash & shooter duality game",
    youtubeID: "ra7FCriWLSk",
    websiteLink: null,
    logoPath: "UEWhite.png",
    imageFileName: "Immortal.jpg",
    extraImages: ["ImmortalE1.jpg", "ImmortalE2.jpg", "ImmortalE3.jpg"],
  },
  {
    title: "NoLongerMe",
    desc: "Game jam entry",
    youtubeID: "oTfJH3pV1Is",
    websiteLink: null,
    logoPath: "UEWhite.png",
    imageFileName: "NoLongerMe.webp",
    extraImages: ["NoLongerMeE1.jpg", "NoLongerMeE2.jpg", "NoLongerMeE3.jpg"],
  },
  {
    title: "Python Basics",
    desc: "1 day GameJam entry",
    youtubeID: "mWL9KU680SY",
    websiteLink: null,
    logoPath: "Unity.png",
    imageFileName: "HackYourLearningMain.jpg",
    extraImages: [
      "PythonBasicsE1.jpg",
      "PythonBasicsE2.jpg",
      "PythonBasicsE3.jpg",
    ],
  },
  {
    title: "Blender Modeling",
    desc: "Some projects from my modeling experience",
    youtubeID: "rabyhOKTWmA",
    websiteLink: null,
    logoPath: "Blender.png",
    imageFileName: "Blender.jpg",
    extraImages: ["BlenderE1.jpg", "BlenderE2.jpg", "BlenderE3.jpg"],
  },
  {
    title: "Bruh",
    desc: "2D automatic side scroller",
    youtubeID: "cOpqK3E2y80",
    websiteLink: null,
    logoPath: "Unity.png",
    imageFileName: "BruhGame.jpg",
    extraImages: ["BruhGameE1.jpg", "BruhGameE2.jpg", "BruhGameE3.jpg"],
  },
  {
    title: "Scuffed RPG",
    desc: "My very first game",
    youtubeID: "psYUcK-L7qE",
    websiteLink: null,
    logoPath: "Unity.png",
    imageFileName: "ScuffedRPGAdventures.jpg",
    extraImages: ["ScuffedRPGAdventuresE1.jpg", "ScuffedRPGAdventuresE2.jpg", "ScuffedRPGAdventuresE3.jpg"],
  },
  {
    title: "My first Website",
    desc: "My starting point in web development",
    youtubeID: null,
    websiteLink:
      "https://kaitosugimura.github.io/Archive_KaitoSugimura.github.io/",
    logoPath: "JavaScript.png",
    imageFileName: "KaitoWebsite.jpg",
    extraImages: [
      "KaitoWebsiteE1.jpg",
      "KaitoWebsiteE2.jpg",
      "KaitoWebsiteE3.jpg",
    ],
  },
];
