// Main Image file must be put in /public/Home/WebsiteProjects/
// Extra images file must be put in /public/Home/WebsiteProjects/Extra

export default [
  {
    imageFileName: "ImSlimeMain.jpg",
    logoPath: "React.png",
    title: "I'm Slime",
    youtubeID: "F0mAtFBdw5w",
    desc: "Online Multiplayer Game",
    extraImages: ["ImSlimeE1.jpg", "ImSlimeE2.jpg", "ImSlimeE3.jpg"],
  },
  {
    imageFileName: "2.jpg",
    logoPath: "UEWhite.png",
    title: "I'm Slime",
    imageFileName: "ImSlimeMain.jpg",
    youtubeID: "0saw1cGIl1A",
    desc: "Description",
    extraImages: ["z.gif", "z.gif", "z.gif"],
  },
  {
    imageFileName: "3.png",
    logoPath: "UEWhite.png",
    title: "Zekka",
    imageFileName: "CoinDozerGame.jpg",
    youtubeID: "0saw1cGIl1A",
    desc: "RPG coin dozer with events",
    extraImages: ["2a.jpg", "2b.jpg", "2c.jpg"],
  },
  {
    imageFileName: "4.jpg",
    logoPath: "UEWhite.png",
    title: "I'm Slime",
    imageFileName: "Immortal.jpg",
    youtubeID: "0saw1cGIl1A",
    desc: "Description Description Description Description Description Description",
    extraImages: ["3a.jpg", "3b.jpg", "3c.jpg"],
  },
  {
    imageFileName: "5.jpg",
    logoPath: "UEWhite.png",
    title: "I'm Slime",
    imageFileName: "NoLongerMe.webp",
    youtubeID: "0saw1cGIl1A",
    desc: "Description",
    extraImages: ["4a.jpg", "4b.jpg", "4c.jpg"],
  },
  {
    imageFileName: "6.jpg",
    logoPath: "Unity.png",
    title: "Python Basics",
    imageFileName: "HackYourLearningMain.jpg",
    youtubeID: "0saw1cGIl1A",
    desc: "Description",
    extraImages: ["5a.jpg", "5b.jpg", "5c.jpg"],
  },
  {
    imageFileName: "7.jpg",
    logoPath: "Blender.png",
    title: "I'm Slime",
    imageFileName: "BlenderModel.jpg",
    youtubeID: "PgBvV9ofjmA",
    desc: "Description",
    extraImages: ["1a.jpg", "1b.jpg", "1c.jpg"],
  },
  {
    imageFileName: "8.jpg",
    logoPath: "UEWhite.png",
    title: "I'm Slime",
    imageFileName: "ImSlimeMain.jpg",
    youtubeID: "PgBvV9ofjmA",
    desc: "Description",
    extraImages: ["1a.jpg", "1b.jpg", "1c.jpg"],
  },
  {
    imageFileName: "9.jpg",
    logoPath: "UEWhite.png",
    title: "I'm Slime",
    imageFileName: "ImSlimeMain.jpg",
    youtubeID: "PgBvV9ofjmA",
    desc: "Description",
    extraImages: ["1a.jpg", "1b.jpg", "1c.jpg"],
  },
];
